name: primware
description: "A primware app for managing and sharing your primware collection."
publish_to: "none"
version: 0.1.18+18

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  top_snackbar_flutter: ^3.2.0
  intl: ^0.20.2
  dropdown_search: ^6.0.2
  flutter_launcher_icons: ^0.14.3
  shimmer: ^3.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.1
  http: ^1.4.0
  searchfield: ^1.3.2
  flutter_localization: ^0.3.3
  fl_chart: ^1.0.0


flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/img/icono.png"
    background_color: "#FAFAFA"
    theme_color: "#FAFAFA"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icono.png"
  windows:
    generate: true
    image_path: "assets/img/icono.png"
    icon_size: 48


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
